/**
 * Plantillas prediseñadas para ATE
 * Permiten a los docentes comenzar rápidamente con estructuras preconfiguradas
 */

export interface ATETemplate {
  id: string;
  name: string;
  description: string;
  discipline: string;
  grade: string;
  duration: string;
  icon: string;
  color: string;
  data: any;
}

export const templates: ATETemplate[] = [
  {
    id: "template-project-based",
    name: "Aprendizaje Basado en Proyectos",
    description: "Plantilla para proyectos donde los estudiantes construyen soluciones a problemas reales",
    discipline: "Multidisciplinario",
    grade: "7-11",
    duration: "60-120 min",
    icon: "🏗️",
    color: "from-blue-600 to-cyan-600",
    data: {
      projectName: "[Tu Proyecto]",
      secretCode: "TEMPLATE-001",
      disciplinaryArea: "[Área disciplinaria]",
      grade: "[Grado]",
      members: ["Estudiante 1", "Estudiante 2"],
      learningObjective: "Los estudiantes [verbo de Bloom] [concepto clave] mediante la construcción de [solución/producto].",
      pedagogicalStrategy: "Aprendizaje basado en proyectos con construccionismo",
      strategyJustification: "Permite que los estudiantes construyan soluciones reales a problemas auténticos, desarrollando pensamiento crítico y habilidades prácticas.",
      technology: "[Herramientas tecnológicas específicas]",
      technologyType: "[Tipo de tecnología: herramientas, software, hardware]",
      technologyCost: "Bajo",
      contentRepresentation: "Práctica e interactiva",
      strategyPotentiation: "Alta - integra múltiples disciplinas",
      totalDuration: "90",
      openingDuration: "15",
      openingTeacherRole: "[Describe el rol del docente en la apertura]",
      openingStudentRole: "[Describe el rol del estudiante en la apertura]",
      developmentDuration: "60",
      developmentTeacherRole: "[Describe el rol del docente en el desarrollo]",
      developmentStudentRole: "[Describe el rol del estudiante en el desarrollo]",
      closingDuration: "15",
      closingTeacherRole: "[Describe el rol del docente en el cierre]",
      closingStudentRole: "[Describe el rol del estudiante en el cierre]",
      technicalResources: [],
      referenceFiles: [],
    }
  },
  {
    id: "template-lab-based",
    name: "Aprendizaje Basado en Laboratorio",
    description: "Plantilla para actividades experimentales con análisis digital de datos",
    discipline: "Ciencias Naturales",
    grade: "8-11",
    duration: "90-120 min",
    icon: "🧪",
    color: "from-green-600 to-emerald-600",
    data: {
      projectName: "[Tu Experimento]",
      secretCode: "TEMPLATE-LAB-001",
      disciplinaryArea: "[Biología/Química/Física]",
      grade: "[Grado]",
      members: ["Estudiante 1", "Estudiante 2"],
      learningObjective: "Los estudiantes realizarán [experimento] y analizarán los datos utilizando [herramientas digitales].",
      pedagogicalStrategy: "Aprendizaje basado en laboratorio con análisis digital",
      strategyJustification: "Integra la experimentación práctica con análisis digital para profundizar en la comprensión científica.",
      technology: "[Software de análisis, instrumentos digitales]",
      technologyType: "Herramientas de laboratorio y análisis",
      technologyCost: "Medio",
      contentRepresentation: "Práctica y digital",
      strategyPotentiation: "Alta - conecta laboratorio con ciencia real",
      totalDuration: "120",
      openingDuration: "20",
      openingTeacherRole: "[Explicación del experimento y protocolo]",
      openingStudentRole: "[Comprensión del objetivo y procedimiento]",
      developmentDuration: "80",
      developmentTeacherRole: "[Supervisión y guía durante el experimento]",
      developmentStudentRole: "[Realización del experimento y recolección de datos]",
      closingDuration: "20",
      closingTeacherRole: "[Facilitación del análisis y conclusiones]",
      closingStudentRole: "[Análisis de datos y presentación de resultados]",
      technicalResources: [],
      referenceFiles: [],
    }
  },
  {
    id: "template-creative",
    name: "Aprendizaje Creativo con Tecnología",
    description: "Plantilla para proyectos creativos que integran arte, diseño y tecnología",
    discipline: "Artes, Diseño, Tecnología",
    grade: "7-11",
    duration: "75-100 min",
    icon: "🎨",
    color: "from-purple-600 to-pink-600",
    data: {
      projectName: "[Tu Proyecto Creativo]",
      secretCode: "TEMPLATE-CREATIVE-001",
      disciplinaryArea: "[Artes/Diseño/Tecnología]",
      grade: "[Grado]",
      members: ["Estudiante 1", "Estudiante 2"],
      learningObjective: "Los estudiantes crearán [obra/proyecto] utilizando [herramientas creativas] demostrando [habilidades específicas].",
      pedagogicalStrategy: "Aprendizaje basado en proyectos creativos",
      strategyJustification: "Integra la expresión artística con tecnología para crear experiencias significativas y desarrollar pensamiento creativo.",
      technology: "[Software de diseño, herramientas creativas]",
      technologyType: "Herramientas de diseño y creación",
      technologyCost: "Bajo",
      contentRepresentation: "Visual e interactiva",
      strategyPotentiation: "Alta - combina arte, creatividad e innovación",
      totalDuration: "90",
      openingDuration: "15",
      openingTeacherRole: "[Inspiración y presentación de ejemplos]",
      openingStudentRole: "[Exploración de posibilidades creativas]",
      developmentDuration: "60",
      developmentTeacherRole: "[Facilitación y retroalimentación]",
      developmentStudentRole: "[Creación y experimentación]",
      closingDuration: "15",
      closingTeacherRole: "[Evaluación y reflexión]",
      closingStudentRole: "[Presentación y autoevaluación]",
      technicalResources: [],
      referenceFiles: [],
    }
  },
  {
    id: "template-research",
    name: "Aprendizaje Basado en Investigación",
    description: "Plantilla para actividades de investigación con recolección y análisis de datos",
    discipline: "Multidisciplinario",
    grade: "8-11",
    duration: "120-150 min",
    icon: "🔬",
    color: "from-orange-600 to-red-600",
    data: {
      projectName: "[Tu Investigación]",
      secretCode: "TEMPLATE-RESEARCH-001",
      disciplinaryArea: "[Área de investigación]",
      grade: "[Grado]",
      members: ["Estudiante 1", "Estudiante 2", "Estudiante 3"],
      learningObjective: "Los estudiantes investigarán [pregunta de investigación] recolectando y analizando datos para [objetivo].",
      pedagogicalStrategy: "Aprendizaje basado en investigación científica",
      strategyJustification: "Desarrolla habilidades de investigación, pensamiento crítico y capacidad de análisis mediante procesos científicos reales.",
      technology: "[Herramientas de recolección y análisis de datos]",
      technologyType: "Herramientas de investigación y análisis",
      technologyCost: "Medio",
      contentRepresentation: "Datos y análisis",
      strategyPotentiation: "Alta - desarrolla pensamiento científico",
      totalDuration: "120",
      openingDuration: "20",
      openingTeacherRole: "[Presentación de la pregunta de investigación]",
      openingStudentRole: "[Formulación de hipótesis]",
      developmentDuration: "80",
      developmentTeacherRole: "[Guía del proceso de investigación]",
      developmentStudentRole: "[Recolección y análisis de datos]",
      closingDuration: "20",
      closingTeacherRole: "[Facilitación de conclusiones]",
      closingStudentRole: "[Presentación de hallazgos]",
      technicalResources: [],
      referenceFiles: [],
    }
  },
  {
    id: "template-collaborative",
    name: "Aprendizaje Colaborativo Mediado por Tecnología",
    description: "Plantilla para proyectos colaborativos donde los estudiantes trabajan en equipo utilizando herramientas digitales",
    discipline: "Multidisciplinario",
    grade: "6-11",
    duration: "60-90 min",
    icon: "👥",
    color: "from-indigo-600 to-blue-600",
    data: {
      projectName: "[Tu Proyecto Colaborativo]",
      secretCode: "TEMPLATE-COLLAB-001",
      disciplinaryArea: "[Área disciplinaria]",
      grade: "[Grado]",
      members: ["Equipo 1", "Equipo 2", "Equipo 3"],
      learningObjective: "Los estudiantes colaborarán en [proyecto] utilizando [herramientas digitales] para [objetivo compartido].",
      pedagogicalStrategy: "Aprendizaje colaborativo con herramientas digitales",
      strategyJustification: "Desarrolla habilidades de comunicación, trabajo en equipo y resolución colaborativa de problemas mediante tecnología.",
      technology: "[Herramientas colaborativas: Google Workspace, Padlet, Trello, etc.]",
      technologyType: "Herramientas de colaboración digital",
      technologyCost: "Bajo",
      contentRepresentation: "Colaborativa y compartida",
      strategyPotentiation: "Alta - desarrolla habilidades del siglo XXI",
      totalDuration: "90",
      openingDuration: "15",
      openingTeacherRole: "[Explicación de la tarea colaborativa]",
      openingStudentRole: "[Formación de equipos y asignación de roles]",
      developmentDuration: "60",
      developmentTeacherRole: "[Facilitación de la colaboración]",
      developmentStudentRole: "[Trabajo colaborativo en equipo]",
      closingDuration: "15",
      closingTeacherRole: "[Evaluación de la colaboración]",
      closingStudentRole: "[Presentación de resultados conjuntos]",
      technicalResources: [],
      referenceFiles: [],
    }
  },
  {
    id: "template-immersive",
    name: "Aprendizaje Inmersivo con Realidad Aumentada/Virtual",
    description: "Plantilla para experiencias inmersivas que utilizan AR/VR para aprendizaje experiencial",
    discipline: "Multidisciplinario",
    grade: "8-11",
    duration: "90-120 min",
    icon: "🥽",
    color: "from-cyan-600 to-blue-600",
    data: {
      projectName: "[Tu Experiencia Inmersiva]",
      secretCode: "TEMPLATE-IMMERSIVE-001",
      disciplinaryArea: "[Área disciplinaria]",
      grade: "[Grado]",
      members: ["Estudiante 1", "Estudiante 2"],
      learningObjective: "Los estudiantes experimentarán [concepto/evento] mediante [tecnología AR/VR] para [objetivo de aprendizaje].",
      pedagogicalStrategy: "Aprendizaje experiencial inmersivo",
      strategyJustification: "Las experiencias inmersivas proporcionan contexto vivencial que profundiza la comprensión y retención del conocimiento.",
      technology: "[Herramientas AR/VR: CoSpaces, Merge Cube, Google Expeditions, etc.]",
      technologyType: "Herramientas de realidad aumentada/virtual",
      technologyCost: "Medio-Alto",
      contentRepresentation: "Inmersiva y experiencial",
      strategyPotentiation: "Alta - transforma la experiencia de aprendizaje",
      totalDuration: "120",
      openingDuration: "20",
      openingTeacherRole: "[Introducción a la experiencia inmersiva]",
      openingStudentRole: "[Preparación y orientación]",
      developmentDuration: "80",
      developmentTeacherRole: "[Facilitación de la experiencia]",
      developmentStudentRole: "[Exploración inmersiva]",
      closingDuration: "20",
      closingTeacherRole: "[Reflexión y análisis]",
      closingStudentRole: "[Reflexión sobre la experiencia]",
      technicalResources: [],
      referenceFiles: [],
    }
  },
];

export const getTemplateById = (id: string): ATETemplate | undefined => {
  return templates.find(t => t.id === id);
};

export const getTemplatesByDiscipline = (discipline: string): ATETemplate[] => {
  return templates.filter(t => 
    t.discipline.toLowerCase().includes(discipline.toLowerCase()) || 
    discipline.toLowerCase().includes("multidisciplinario")
  );
};
